# Site settings
author: T. Roman
title: The Code Less Traveled
header-img: img/home-bg.png
email: romantabatha17@gmail.com
copyright_name: T. Roman
description: > # this means to ignore newlines until "baseurl:"
  The Journey to Become a Software Engineer 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  romantabatha

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
